apiVersion: v1
kind: Service
metadata:
  name: web-frontend
  namespace: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: web-frontend
status:
  loadBalancer: {}
