apiVersion: v1
kind: Pod
metadata:
  labels:
    run: file-writer
  name: file-writer
  namespace: ckad-exam
spec:
  volumes:
  - name: shared-data
    persistentVolumeClaim:
      claimName: shared-data
  containers:
  - args:
    - sh
    - -c
    - echo "ckad-practice" > /mnt/data/result.txt && sleep 3600
    image: busybox
    name: file-writer
    volumeMounts:
    - name: shared-data
      mountPath: /mnt/data
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
