apiVersion: apps/v1
kind: Deployment
metadata:
  name: yaml-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: app
          image: nginx
status:
