apiVersion: v1
kind: Pod
metadata:
  labels:
    run: yaml-pod
  name: yaml-pod
spec:
  containers:
  - image: nginx
    name: yaml-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
